/**
 * Todos los textos de la interfaz, en español e inglés.
 *
 * El español es el original: si una clave falta en inglés, se muestra la
 * española en su lugar. Mejor una frase en otro idioma que un
 * identificador suelto en pantalla.
 */
export const TEXTOS = {
  es: {
    // ── Comunes ──────────────────────────────────────────────────────
    cargando: 'Cargando…',
    guardar: 'Guardar cambios',
    guardando: 'Guardando…',
    cancelar: 'Cancelar',
    enviando: 'Enviando…',
    aprobar: 'Aprobar',
    rechazar: 'Rechazar',
    recargar: 'Recargar',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    sinFoto: 'Sin foto',
    idioma: 'Idioma',

    // ── Navegación ───────────────────────────────────────────────────
    navDescubrir: 'Descubrir',
    navMatches: 'Matches',
    navValoraciones: 'Valoraciones',
    navPerfil: 'Mi perfil',
    navAdmin: 'Panel de administración',
    navSalir: 'Salir',

    // ── Entrar y registrarse ─────────────────────────────────────────
    lema: 'Match de servicios domésticos',
    // La franja de la portada: es lo único que explica de qué va esto a
    // quien llega por primera vez y todavía no tiene cuenta.
    reclamoNecesitas: '¿Qué necesitas?',
    reclamoOfreces: '¿Qué ofreces?',
    reclamoQueEs: 'Alguien lo busca, alguien lo hace.',
    reclamoComoVa: 'Cuando el interés es mutuo, se abren los teléfonos y seguís por WhatsApp.',
    reclamoGratis: 'Gratis',
    reclamoSinComisiones: 'Sin comisiones',
    reclamoSinIntermediarios: 'Sin intermediarios',
    bienvenido: 'Bienvenido',
    accede: 'Accede',
    cifraServicios: 'servicios',
    cifraCategorias: 'categorías',
    cifraProvincias: 'provincias',
    entraParaSeguir: 'Inicia sesión para continuar',
    email: 'Email',
    usuarioOEmail: 'Usuario o email',
    contrasena: 'Contraseña',
    entrar: 'Iniciar sesión',
    sinCuenta: '¿No tienes cuenta?',
    registrate: 'Regístrate',
    yaTienesCuenta: '¿Ya tienes cuenta?',
    iniciaSesion: 'Inicia sesión',
    credencialesMal: 'Email o contraseña incorrectos',

    crearCuenta: 'Crear cuenta',
    creandoCuenta: 'Creando cuenta...',
    eligeLado: 'Elige si buscas un servicio o si lo ofreces',
    buscoServicio: 'Busco un servicio',
    ofrezcoServicio: 'Ofrezco mi servicio',
    nombre: 'Nombre',
    contrasenaMinima: 'Contraseña (8 caracteres, con letras y números)',
    whatsapp: 'WhatsApp',
    whatsappEjemplo: 'WhatsApp (+34 600 000 000)',
    telefonoOculto: 'Tu teléfono permanece oculto. Solo se revela cuando hay match por ambas partes.',
    provincia: 'Provincia',
    municipio: 'Municipio',
    eligeProvincia: 'Elige provincia',
    eligeAntesProvincia: 'Elige antes la provincia',
    cargandoMunicipios: 'Cargando municipios…',
    eligeMunicipio: 'Elige municipio ({n})',
    eligeServicio: 'Elige un servicio',
    resumen: 'Resumen',
    resumenNota: '{n}/{max} · lo revisa el equipo antes de publicarse',
    aceptoCondiciones: 'Soy mayor de 18 años y he leído y acepto el',
    enlaceCondiciones: 'aviso legal, las condiciones de uso y la política de privacidad',
    porHora: 'por hora',
    porDia: 'por día',

    errContrasenaCorta: 'La contraseña debe tener al menos 8 caracteres, con letras y números',
    errTelefono: 'Escribe un teléfono de WhatsApp válido, por ejemplo +34 600 000 000',
    errServicio: 'Elige el servicio',
    errUbicacion: 'Elige tu provincia y tu municipio',
    errCondiciones: 'Debes aceptar el aviso legal y la política de privacidad',
    errCorreoUsado: 'Ya existe una cuenta con ese email',

    // ── Descubrir ────────────────────────────────────────────────────
    profesionalesDisponibles: 'Profesionales disponibles',
    clientesQueBuscan: 'Clientes que buscan',
    instruccionDeslizar: 'Desliza a la derecha si te interesa, a la izquierda si no.',
    todosLosServicios: 'Todos los servicios',
    todaEspana: 'Toda España',
    todaLaProvincia: 'Toda la provincia',
    cualquierPrecio: 'Cualquier precio',
    hastaPrecio: 'Hasta {n} €',
    buscando: 'Buscando…',
    mazoVacio: 'No queda nadie por ver con estos filtros.',
    volverABuscar: 'Volver a buscar',
    meInteresa: 'ME INTERESA',
    paso: 'PASO',
    deshacer: 'Recuperar a {nombre}',
    nadaQueDeshacer: 'Nada que deshacer',
    esUnMatch: '¡Es un match!',
    textoMatch: 'Tú y {nombre} os habéis elegido. Ya podéis ver vuestros teléfonos en la sección Matches.',
    seguirMirando: 'Seguir mirando',

    // ── Tarjeta ──────────────────────────────────────────────────────
    etiquetaBusco: 'Busco',
    etiquetaOfrezco: 'Ofrezco',
    visibleAlMatch: 'Visible al hacer match',
    soloLoVesTu: 'Solo lo ves tú. Se revela cuando hagas match.',
    cuentaSuspendidaTarjeta: 'Cuenta suspendida. Sus datos de contacto ya no están disponibles.',

    // ── Matches ──────────────────────────────────────────────────────
    tusMatches: 'Tus matches',
    subtituloMatches: 'Aquí ya podéis veros el teléfono y hablar por WhatsApp.',
    sinMatches: 'Todavía no tienes ningún match.',
    sinMatchesNota: 'Hace falta que las dos partes se marquen mutuamente.',
    pedirValoracion: 'Pedirle que me valore',
    peticionEnviada: 'Petición de valoración enviada',
    retirar: 'Retirar',
    retirando: 'Retirando…',
    yaTeValoro: 'Ya te ha valorado con {n} estrellas',
    eliminarMatch: 'Eliminar match',
    confirmarEliminarMatch: '¿Eliminar tu match con {nombre}?\n\nDejaréis de ver vuestros teléfonos y no volverá a aparecerte en Descubrir. No se puede deshacer.',

    // ── Valoraciones ─────────────────────────────────────────────────
    valoraciones: 'Valoraciones',
    subtituloValoraciones: 'Solo puedes puntuar a quien te lo haya pedido, y una sola vez: la valoración no se puede cambiar.',
    tePidenValorar: 'Te piden que les valores',
    nadieTePide: 'Nadie te ha pedido valoración por ahora.',
    yaHasValorado: 'Ya has valorado',
    definitiva: 'definitiva',
    hasPedidoA: 'Has pedido valoración a',
    noHasPedido: 'No has pedido ninguna. Puedes hacerlo desde cada match, en la pestaña Matches.',
    teHaValorado: 'te ha valorado',
    aunNoTeHaValorado: 'aún no te ha valorado',
    confirmarVoto: 'Vas a valorar a {nombre} con {n} {unidad}.\n\nLa valoración es definitiva: no podrás cambiarla ni retirarla después.',
    estrella: 'estrella',
    estrellas: 'estrellas',
    errRetiroPeticion: 'Esa persona ha retirado su petición de valoración',
    errYaValorada: 'Ya la has valorado, y la valoración no se puede cambiar',

    // ── Mi perfil ────────────────────────────────────────────────────
    miPerfil: 'Mi perfil',
    subtituloPerfil: 'Así te ven los demás. Tu teléfono nunca aparece sin match.',
    cambiosGuardados: 'Cambios guardados',
    fotoActualizada: 'Foto actualizada',
    aparecerEnBusquedas: 'Aparecer en las búsquedas',
    misDatos: 'Mis datos',
    descargarDatos: 'Descarga tu perfil, matches, valoraciones y decisiones',
    descargaLista: 'Descarga preparada',
    eliminarCuenta: 'Eliminar cuenta',
    eliminarCuentaAviso: 'Eliminar tu cuenta y todo su contenido',
    eliminarCuentaTitulo: 'Eliminar mi cuenta',
    eliminarCuentaTexto: 'Se borrarán tu perfil, tu foto, tus matches y tus valoraciones. Quien haya hecho match contigo dejará de ver tu teléfono.',
    noSePuedeDeshacer: 'No se puede deshacer.',
    escribeBorrar: 'Escribe {palabra} para confirmar',
    palabraBorrar: 'BORRAR',
    eliminarDefinitivamente: 'Eliminar mi cuenta definitivamente',
    eliminando: 'Eliminando…',
    denunciasEnviadas: 'Denuncias que has enviado',
    quitarDeLista: 'Quitar de la lista',
    enRevision: 'en revisión',
    revisadaConMedidas: 'revisada, se tomaron medidas',
    revisadaSinMedidas: 'revisada, sin medidas',

    // ── Foto ─────────────────────────────────────────────────────────
    anadeFoto: 'Añade tu foto',
    cambiarFoto: 'Cambiar la foto',
    sueltaFoto: 'Suelta aquí tu foto',
    instruccionFoto: 'Arrástrala, pégala o pulsa para elegirla · JPG o PNG, hasta 25 MB',
    errNoEsImagen: 'Eso no es una imagen. Sube un JPG o un PNG.',
    errFotoPesa: 'La foto pesa {mb} MB y el máximo son 25. Reduce su tamaño.',
    errFotoNoEncoge: 'Este navegador no sabe abrir esa foto y pesa demasiado para subirla tal cual. Prueba a guardarla como JPG.',
    fotoPendiente: 'Pendiente de revisión — aún no se ve en tu tarjeta',
    fotoAprobada: 'Aprobada y visible',
    fotoRechazada: 'Rechazada por el equipo — sube otra',
    textoPendiente: 'Pendiente de revisión — aún no se ve en tu tarjeta',
    textoAprobado: 'Aprobado y visible',
    textoRechazado: 'Rechazado por el equipo — edítalo y vuelve a enviarlo',

    // ── Denuncias ────────────────────────────────────────────────────
    denunciarPerfil: 'Denunciar este perfil',
    queOcurreCon: '¿Qué ocurre con {nombre}?',
    eligeMotivo: 'Elige el motivo',
    cuentanosQuePaso: 'Cuéntanos lo que ha pasado (opcional)',
    enviarDenuncia: 'Enviar denuncia',
    denunciaEnviada: 'Denuncia enviada. La revisaremos lo antes posible.',
    errYaDenunciado: 'Ya denunciaste a esta persona. Estamos revisándolo.',

    // ── Cuenta suspendida ────────────────────────────────────────────
    cuentaSuspendida: 'Cuenta suspendida',
    textoSuspension: 'Tu cuenta ha sido suspendida y no puedes usar CleanDerApp por ahora. Tu perfil no aparece en las búsquedas y quienes hicieron match contigo ya no ven tus datos de contacto.',
    motivo: 'Motivo:',
    siCreesError: 'Si crees que es un error o quieres que revisemos la decisión, escríbenos:',
    cerrarSesion: 'Cerrar sesión',

    // ── Pie ──────────────────────────────────────────────────────────
    derechosReservados: '© {anyo} CleanDerApp. Todos los derechos reservados.',
    avisoLegalEnlace: 'Aviso legal y privacidad',
    sobreNosotros: 'Sobre nosotros',

    // ── Según el rol ─────────────────────────────────────────────────
    precioCliente: 'Pago por {unidad}',
    precioServicio: 'Cobro por {unidad}',
    categoriaCliente: 'Servicio que necesito',
    categoriaServicio: 'Servicio que ofrezco',
    resumenCliente: 'Qué necesitas exactamente (máx. {max} caracteres)',
    resumenServicio: 'Qué ofreces y tu experiencia (máx. {max} caracteres)',

    // ── Panel de administración ──────────────────────────────────────
    panelTitulo: 'Panel de administración',
    panelSubtitulo: 'Control total sobre usuarios, textos y matches.',
    statClientes: 'Clientes',
    statServicios: 'Servicios',
    statMatches: 'Matches',
    statLikes: 'Me interesa',
    statBloqueados: 'Bloqueados',
    statTextos: 'Textos por revisar',
    statFotos: 'Fotos por revisar',
    statDenuncias: 'Denuncias',
    pestanaUsuarios: 'Usuarios',
    pestanaDenuncias: 'Denuncias',
    buscarUsuario: 'Buscar por nombre, email, ciudad, teléfono…',
    todosLosRoles: 'Todos los roles',
    soloPendientes: 'Solo pendientes de revisar',
    usarIcono: 'Quitar la foto y usar el icono de mi oficio',
    sinFotoIcono: 'Sin foto se usa el icono de tu oficio, como en la vista previa de arriba.',
    fotoQuitada: 'Foto quitada. Tu tarjeta vuelve a usar el icono de tu oficio.',
    ocultarMuestra: 'Ocultar perfiles de muestra',
    colUsuario: 'Usuario',
    colFoto: 'Foto',
    colRol: 'Rol',
    colContacto: 'Contacto',
    colServicio: 'Servicio',
    colResumen: 'Resumen',
    colMatches: 'Matches',
    colAcciones: 'Acciones',
    verPerfil: 'Ver perfil',
    bloquear: 'Bloquear',
    desbloquear: 'Desbloquear',
    ocultar: 'Ocultar',
    mostrar: 'Mostrar',
    borrar: 'Borrar',
    sinTexto: 'sin texto',
    nadieCoincide: 'Ningún usuario coincide con el filtro.',
    sinDenuncias: 'No hay ninguna denuncia.',
    contra: 'Contra',
    bloqueadoEtiqueta: 'bloqueado',
    bloquearYCerrar: 'Bloquear y cerrar',
    marcarRevisada: 'Marcar revisada',
    descartar: 'Descartar',
    de: 'De',
    paginaDe: '{actual} de {total} · {n} usuarios',
    preguntaMotivoBloqueo: '¿Por qué bloqueas a {nombre}?\n\nLo leerá en la pantalla de cuenta suspendida. Déjalo vacío si prefieres no decirlo.',
    confirmarBorrado: '¿Borrar definitivamente a {nombre}?\n\nSe eliminarán su perfil, sus matches y sus valoraciones. No se puede deshacer.',

    // ── Ficha de usuario ─────────────────────────────────────────────
    rolAdmin: 'Administración',
    rolCliente: 'Busca servicio',
    rolServicio: 'Ofrece servicio',
    fichaDonde: 'Dónde',
    fichaPrecio: 'Precio',
    fichaAlta: 'Alta',
    fichaDecisiones: 'Decisiones',
    fichaSi: 'sí',
    fichaNo: 'no',
    fichaDescripcion: 'Su descripción',
    fichaDenuncias: 'Denuncias recibidas ({n})',
    fichaSinMatches: 'Ninguno todavía.',
    fichaRecibidas: 'Recibidas:',
    fichaDadas: 'Dadas:',
    fichaNinguna: 'ninguna',
    aprobarTexto: 'Aprobar texto',
    rechazarTexto: 'Rechazar texto',
    cerrar: 'Cerrar',
    estadoPendiente: 'pendiente',
    estadoAprobado: 'aprobado',
    estadoRechazado: 'rechazado',
    etiquetaFoto: 'foto',
    etiquetaTexto: 'texto',

    // ── Contraseñas y recuperación ──────────────────────────────────
    olvidoContrasena: '¿Has olvidado la contraseña?',
    recuperarTitulo: 'Recuperar el acceso',
    recuperarSubtitulo: 'Te mandamos un enlace para poner una contraseña nueva',
    enviarEnlace: 'Enviarme el enlace',
    recuperarEnviado: 'Si ese correo tiene cuenta, en un momento recibirás un enlace para cambiar la contraseña.',
    recuperarRevisaSpam: 'Si no lo ves, mira en la carpeta de correo no deseado.',
    teAcuerdas: '¿Ya te acuerdas?',
    volverAlLogin: 'Volver a iniciar sesión',

    nuevaClaveTitulo: 'Contraseña nueva',
    nuevaClaveSubtitulo: 'Escríbela dos veces para que no haya dudas',
    nuevaClaveHecho: 'Listo. Tu contraseña ya está cambiada.',
    guardarYEntrar: 'Guardar y entrar',

    contrasenaNueva: 'Contraseña nueva',
    repiteContrasena: 'Repite la contraseña',
    guardarContrasena: 'Guardar contraseña',
    cambiarContrasena: 'Cambiar la contraseña',
    contrasenaCambiada: 'Contraseña cambiada',

    cuentaCreada: 'Cuenta creada',
    confirmaTuCorreo: 'Te hemos escrito a {correo}. Pincha el enlace del mensaje para confirmar la cuenta y ya podrás entrar.',
    fotoTrasConfirmar: 'Tu foto no se ha subido todavía: añádela desde Mi perfil en cuanto entres.',

    sinTelefono: 'Sin teléfono',

    // ── Errores ─────────────────────────────────────────────────────
    errGenerico: 'Algo no ha ido bien. Vuelve a intentarlo en un momento.',
    errSinConexion: 'No hemos podido conectar. Comprueba tu conexión e inténtalo otra vez.',
    errSinConfirmar: 'Todavía no has confirmado tu cuenta. Busca el correo que te mandamos y pincha el enlace.',
    errCorreoInvalido: 'Esa dirección de correo no parece válida.',
    errContrasenaDebil: 'Esa contraseña es demasiado fácil de adivinar o ha aparecido en filtraciones. Elige otra.',
    errContrasenaIgual: 'La contraseña nueva tiene que ser distinta de la anterior.',
    errVuelveAEntrar: 'Por seguridad, cierra sesión y vuelve a entrar antes de cambiar la contraseña.',
    errClavesNoCoinciden: 'Las dos contraseñas no coinciden.',
    errDemasiadosIntentos: 'Has hecho demasiados intentos seguidos. Espera un minuto y vuelve a probar.',
    errEnlaceCaducado: 'Ese enlace ya no vale. Pide uno nuevo.',
    errMatchNoEncontrado: 'Ese match ya no existe.',

  },

  en: {
    cargando: 'Loading…',
    guardar: 'Save changes',
    guardando: 'Saving…',
    cancelar: 'Cancel',
    enviando: 'Sending…',
    aprobar: 'Approve',
    rechazar: 'Reject',
    recargar: 'Reload',
    anterior: 'Previous',
    siguiente: 'Next',
    sinFoto: 'No photo',
    idioma: 'Language',

    navDescubrir: 'Discover',
    navMatches: 'Matches',
    navValoraciones: 'Ratings',
    navPerfil: 'My profile',
    navAdmin: 'Admin panel',
    navSalir: 'Log out',

    lema: 'Home services matchmaking',
    reclamoNecesitas: 'What do you need?',
    reclamoOfreces: 'What do you offer?',
    reclamoQueEs: 'Someone is looking for it, someone does it.',
    reclamoComoVa: 'When both sides are interested, the phone numbers open up and you carry on over WhatsApp.',
    reclamoGratis: 'Free',
    reclamoSinComisiones: 'No commission',
    reclamoSinIntermediarios: 'No middlemen',
    bienvenido: 'Welcome',
    accede: 'Sign in',
    cifraServicios: 'services',
    cifraCategorias: 'categories',
    cifraProvincias: 'provinces',
    entraParaSeguir: 'Log in to continue',
    email: 'Email',
    usuarioOEmail: 'Username or email',
    contrasena: 'Password',
    entrar: 'Log in',
    sinCuenta: "Don't have an account?",
    registrate: 'Sign up',
    yaTienesCuenta: 'Already have an account?',
    iniciaSesion: 'Log in',
    credencialesMal: 'Wrong email or password',

    crearCuenta: 'Create account',
    creandoCuenta: 'Creating account...',
    eligeLado: "Choose whether you're looking for a service or offering one",
    buscoServicio: "I'm looking for a service",
    ofrezcoServicio: 'I offer my service',
    nombre: 'Name',
    contrasenaMinima: 'Password (8 characters, with letters and numbers)',
    whatsapp: 'WhatsApp',
    whatsappEjemplo: 'WhatsApp (+34 600 000 000)',
    telefonoOculto: 'Your phone stays hidden. It is only revealed when both sides match.',
    provincia: 'Province',
    municipio: 'Town',
    eligeProvincia: 'Choose a province',
    eligeAntesProvincia: 'Choose a province first',
    cargandoMunicipios: 'Loading towns…',
    eligeMunicipio: 'Choose a town ({n})',
    eligeServicio: 'Choose a service',
    resumen: 'Summary',
    resumenNota: '{n}/{max} · reviewed by our team before it goes live',
    aceptoCondiciones: 'I am over 18 and I have read and accept the',
    enlaceCondiciones: 'legal notice, terms of use and privacy policy',
    porHora: 'per hour',
    porDia: 'per day',

    errContrasenaCorta: 'The password must be at least 8 characters, with letters and numbers',
    errTelefono: 'Enter a valid WhatsApp number, for example +34 600 000 000',
    errServicio: 'Choose a service',
    errUbicacion: 'Choose your province and town',
    errCondiciones: 'You must accept the legal notice and privacy policy',
    errCorreoUsado: 'An account with that email already exists',

    profesionalesDisponibles: 'Available professionals',
    clientesQueBuscan: 'Clients looking for help',
    instruccionDeslizar: "Swipe right if you're interested, left if you're not.",
    todosLosServicios: 'All services',
    todaEspana: 'All of Spain',
    todaLaProvincia: 'Whole province',
    cualquierPrecio: 'Any price',
    hastaPrecio: 'Up to €{n}',
    buscando: 'Searching…',
    mazoVacio: 'Nobody left to see with these filters.',
    volverABuscar: 'Search again',
    meInteresa: 'INTERESTED',
    paso: 'PASS',
    deshacer: 'Bring back {nombre}',
    nadaQueDeshacer: 'Nothing to undo',
    esUnMatch: "It's a match!",
    textoMatch: 'You and {nombre} have chosen each other. You can now see each other’s phone numbers in Matches.',
    seguirMirando: 'Keep looking',

    etiquetaBusco: 'Looking',
    etiquetaOfrezco: 'Offering',
    visibleAlMatch: 'Visible once you match',
    soloLoVesTu: 'Only you can see this. It is revealed when you match.',
    cuentaSuspendidaTarjeta: 'Suspended account. Their contact details are no longer available.',

    tusMatches: 'Your matches',
    subtituloMatches: 'You can now see each other’s phone and talk on WhatsApp.',
    sinMatches: "You don't have any matches yet.",
    sinMatchesNota: 'Both sides need to pick each other.',
    pedirValoracion: 'Ask them to rate me',
    peticionEnviada: 'Rating request sent',
    retirar: 'Withdraw',
    retirando: 'Withdrawing…',
    yaTeValoro: 'They rated you {n} stars',
    eliminarMatch: 'Remove match',
    confirmarEliminarMatch: 'Remove your match with {nombre}?\n\nYou will both stop seeing each other’s phone and they will not show up in Discover again. This cannot be undone.',

    valoraciones: 'Ratings',
    subtituloValoraciones: 'You can only rate someone who asked you to, and only once: ratings cannot be changed.',
    tePidenValorar: 'They ask you to rate them',
    nadieTePide: 'Nobody has asked you for a rating yet.',
    yaHasValorado: 'Already rated',
    definitiva: 'final',
    hasPedidoA: 'You asked for a rating from',
    noHasPedido: 'You have not asked for any. You can do it from each match, in the Matches tab.',
    teHaValorado: 'rated you',
    aunNoTeHaValorado: 'has not rated you yet',
    confirmarVoto: 'You are about to rate {nombre} {n} {unidad}.\n\nThis is final: you will not be able to change or withdraw it.',
    estrella: 'star',
    estrellas: 'stars',
    errRetiroPeticion: 'That person withdrew their rating request',
    errYaValorada: 'You already rated them, and ratings cannot be changed',

    miPerfil: 'My profile',
    subtituloPerfil: 'This is how others see you. Your phone never shows without a match.',
    cambiosGuardados: 'Changes saved',
    fotoActualizada: 'Photo updated',
    aparecerEnBusquedas: 'Show me in searches',
    misDatos: 'My data',
    descargarDatos: 'Download your profile, matches, ratings and decisions',
    descargaLista: 'Download ready',
    eliminarCuenta: 'Delete account',
    eliminarCuentaAviso: 'Delete your account and everything in it',
    eliminarCuentaTitulo: 'Delete my account',
    eliminarCuentaTexto: 'Your profile, photo, matches and ratings will be deleted. Anyone who matched with you will stop seeing your phone.',
    noSePuedeDeshacer: 'This cannot be undone.',
    escribeBorrar: 'Type {palabra} to confirm',
    palabraBorrar: 'DELETE',
    eliminarDefinitivamente: 'Delete my account permanently',
    eliminando: 'Deleting…',
    denunciasEnviadas: 'Reports you have sent',
    quitarDeLista: 'Remove from list',
    enRevision: 'under review',
    revisadaConMedidas: 'reviewed, action taken',
    revisadaSinMedidas: 'reviewed, no action taken',

    anadeFoto: 'Add your photo',
    cambiarFoto: 'Change photo',
    sueltaFoto: 'Drop your photo here',
    instruccionFoto: 'Drag it, paste it or click to choose · JPG or PNG, up to 25 MB',
    errNoEsImagen: 'That is not an image. Upload a JPG or a PNG.',
    errFotoPesa: 'The photo is {mb} MB and the limit is 25. Make it smaller.',
    errFotoNoEncoge: 'This browser cannot open that photo and it is too large to upload as is. Try saving it as JPG.',
    fotoPendiente: 'Under review — not visible on your card yet',
    fotoAprobada: 'Approved and visible',
    fotoRechazada: 'Rejected by our team — upload a different one',
    textoPendiente: 'Under review — not visible on your card yet',
    textoAprobado: 'Approved and visible',
    textoRechazado: 'Rejected by our team — edit it and send it again',

    denunciarPerfil: 'Report this profile',
    queOcurreCon: 'What is wrong with {nombre}?',
    eligeMotivo: 'Choose a reason',
    cuentanosQuePaso: 'Tell us what happened (optional)',
    enviarDenuncia: 'Send report',
    denunciaEnviada: 'Report sent. We will look into it as soon as possible.',
    errYaDenunciado: 'You already reported this person. We are looking into it.',

    cuentaSuspendida: 'Account suspended',
    textoSuspension: 'Your account has been suspended and you cannot use CleanDerApp for now. Your profile does not appear in searches and people who matched with you can no longer see your contact details.',
    motivo: 'Reason:',
    siCreesError: 'If you think this is a mistake or want us to review the decision, write to us:',
    cerrarSesion: 'Log out',

    derechosReservados: '© {anyo} CleanDerApp. All rights reserved.',
    avisoLegalEnlace: 'Legal notice and privacy',
    sobreNosotros: 'About us',

    precioCliente: 'I pay per {unidad}',
    precioServicio: 'I charge per {unidad}',
    categoriaCliente: 'Service I need',
    categoriaServicio: 'Service I offer',
    resumenCliente: 'What exactly you need (max. {max} characters)',
    resumenServicio: 'What you offer and your experience (max. {max} characters)',

    panelTitulo: 'Admin panel',
    panelSubtitulo: 'Full control over users, texts and matches.',
    statClientes: 'Clients',
    statServicios: 'Providers',
    statMatches: 'Matches',
    statLikes: 'Interested',
    statBloqueados: 'Blocked',
    statTextos: 'Texts to review',
    statFotos: 'Photos to review',
    statDenuncias: 'Reports',
    pestanaUsuarios: 'Users',
    pestanaDenuncias: 'Reports',
    buscarUsuario: 'Search by name, email, town, phone…',
    todosLosRoles: 'All roles',
    soloPendientes: 'Only pending review',
    usarIcono: 'Remove photo and use my trade icon',
    sinFotoIcono: 'With no photo, your trade icon is used, as in the preview above.',
    fotoQuitada: 'Photo removed. Your card uses your trade icon again.',
    ocultarMuestra: 'Hide sample profiles',
    colUsuario: 'User',
    colFoto: 'Photo',
    colRol: 'Role',
    colContacto: 'Contact',
    colServicio: 'Service',
    colResumen: 'Summary',
    colMatches: 'Matches',
    colAcciones: 'Actions',
    verPerfil: 'View profile',
    bloquear: 'Block',
    desbloquear: 'Unblock',
    ocultar: 'Hide',
    mostrar: 'Show',
    borrar: 'Delete',
    sinTexto: 'no text',
    nadieCoincide: 'No user matches the filter.',
    sinDenuncias: 'There are no reports.',
    contra: 'Against',
    bloqueadoEtiqueta: 'blocked',
    bloquearYCerrar: 'Block and close',
    marcarRevisada: 'Mark reviewed',
    descartar: 'Dismiss',
    de: 'From',
    paginaDe: '{actual} of {total} · {n} users',
    preguntaMotivoBloqueo: 'Why are you blocking {nombre}?\n\nThey will read it on the suspended account screen. Leave it empty if you prefer not to say.',
    confirmarBorrado: 'Permanently delete {nombre}?\n\nTheir profile, matches and ratings will be removed. This cannot be undone.',

    rolAdmin: 'Administration',
    rolCliente: 'Looking for a service',
    rolServicio: 'Offering a service',
    fichaDonde: 'Where',
    fichaPrecio: 'Price',
    fichaAlta: 'Joined',
    fichaDecisiones: 'Decisions',
    fichaSi: 'yes',
    fichaNo: 'no',
    fichaDescripcion: 'Their description',
    fichaDenuncias: 'Reports received ({n})',
    fichaSinMatches: 'None yet.',
    fichaRecibidas: 'Received:',
    fichaDadas: 'Given:',
    fichaNinguna: 'none',
    aprobarTexto: 'Approve text',
    rechazarTexto: 'Reject text',
    cerrar: 'Close',
    estadoPendiente: 'pending',
    estadoAprobado: 'approved',
    estadoRechazado: 'rejected',
    etiquetaFoto: 'photo',
    etiquetaTexto: 'text',

    // ── Passwords and recovery ──────────────────────────────────────
    olvidoContrasena: 'Forgotten your password?',
    recuperarTitulo: 'Get back in',
    recuperarSubtitulo: 'We will send you a link to set a new password',
    enviarEnlace: 'Send me the link',
    recuperarEnviado: 'If that address has an account, a link to change the password is on its way.',
    recuperarRevisaSpam: 'If you cannot see it, check your spam folder.',
    teAcuerdas: 'Remembered it?',
    volverAlLogin: 'Back to log in',

    nuevaClaveTitulo: 'New password',
    nuevaClaveSubtitulo: 'Type it twice so there is no doubt',
    nuevaClaveHecho: 'Done. Your password has been changed.',
    guardarYEntrar: 'Save and go in',

    contrasenaNueva: 'New password',
    repiteContrasena: 'Repeat the password',
    guardarContrasena: 'Save password',
    cambiarContrasena: 'Change password',
    contrasenaCambiada: 'Password changed',

    cuentaCreada: 'Account created',
    confirmaTuCorreo: 'We have written to {correo}. Click the link in the message to confirm your account and you can log in.',
    fotoTrasConfirmar: 'Your photo has not been uploaded yet: add it from My profile once you are in.',

    sinTelefono: 'No phone number',

    // ── Errors ──────────────────────────────────────────────────────
    errGenerico: 'Something went wrong. Please try again in a moment.',
    errSinConexion: 'We could not connect. Check your connection and try again.',
    errSinConfirmar: 'You have not confirmed your account yet. Find the email we sent and click the link.',
    errCorreoInvalido: 'That email address does not look valid.',
    errContrasenaDebil: 'That password is too easy to guess or has appeared in a data breach. Choose another one.',
    errContrasenaIgual: 'The new password has to be different from the old one.',
    errVuelveAEntrar: 'For security, log out and back in before changing your password.',
    errClavesNoCoinciden: 'The two passwords do not match.',
    errDemasiadosIntentos: 'Too many attempts in a row. Wait a minute and try again.',
    errEnlaceCaducado: 'That link is no longer valid. Ask for a new one.',
    errMatchNoEncontrado: 'That match no longer exists.',

  },
}
